Add support for list overrides
LinkedSoftwareDependencies/Components.js pull request #134
Opened 2023-12-01 15:00 UTC by joachimvh

Closes https://github.com/LinkedSoftwareDependencies/Components.js/issues/129

Implements what is described in https://github.com/LinkedSoftwareDependencies/Components.js/issues/129#issuecomment-1814630077

Will look into documentation when this is accepted.

Some of the behaviour that happened in the `canHandle` of the `ConfigPreprocessorOverride` was moved to the `transform` call, but this should not have an impact.

2023-12-05 15:01 UTC, rubensworks requested changes
This is a really nice PR, I like it!
Just one minor comment, everything else looks perfect IMO.

Before we merge, could you do a quick check to see if it doesn't break anything in Comunica? (I suspect it won't, since Comunica doesn't use overrides anywhere in any case)

2023-12-07 08:44 UTC, joachimvh commented on lib/preprocess/ConfigPreprocessorOverride.ts
> +    this.stepHandlers = [
No strong opinion either way, just that this was based on how this is done in some other classes: https://github.com/LinkedSoftwareDependencies/Components.js/blob/d33d4c2668974087873943b3d5c66300fa3df65b/lib/preprocess/ConfigPreprocessorComponentMapped.ts#L39-L45 and https://github.com/LinkedSoftwareDependencies/Components.js/blob/a55331085e4c5621832e6b23bc52b00068e8256a/lib/preprocess/ParameterHandler.ts#L21-L27

2023-12-07 09:08 UTC, rubensworks commented on lib/preprocess/ConfigPreprocessorOverride.ts
> +    this.stepHandlers = [
Oh, I see. In that case, you can ignore my comment.

2023-12-08 13:11 UTC, joachimvh commented
Everything seems to work fine when testing with Comunica.

2024-01-09 14:13 UTC, merged

2024-01-09 14:19 UTC, rubensworks commented
Released as 5.5.0.